/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package SOC2;



/**
 *
 * @author usuario_local
 */
public class MainWindow extends javax.swing.JFrame {
    private String rutaCarpeta;

    /**
     * Creates new form NewJFrame
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelNorte = new javax.swing.JPanel();
        jLabelSeleccioneModelo = new javax.swing.JLabel();
        jTabbedPane = new javax.swing.JTabbedPane();
        jTabbedPaneErdosRenry = new javax.swing.JPanel();
        jPanelValorN = new javax.swing.JPanel();
        jLabelValorN = new javax.swing.JLabel();
        jTextFieldN = new javax.swing.JTextField();
        jLabelApunteValorN = new javax.swing.JLabel();
        jPaneValorP = new javax.swing.JPanel();
        jLabelValorP = new javax.swing.JLabel();
        jSliderValorP = new javax.swing.JSlider();
        jTextFieldValorP = new javax.swing.JTextField();
        jPanelCrearRedErdosRenry = new javax.swing.JPanel();
        jButtonCrearRedErdosRenry = new javax.swing.JButton();
        jTabbedPaneBarabasiAlbert = new javax.swing.JPanel();
        jPanelValorM = new javax.swing.JPanel();
        jLabelValorM = new javax.swing.JLabel();
        jTextFieldValorM = new javax.swing.JTextField();
        jPanelValorT = new javax.swing.JPanel();
        jLabelValorT = new javax.swing.JLabel();
        jTextFieldValorT = new javax.swing.JTextField();
        jPanelCrearRedBarabasiAlbert = new javax.swing.JPanel();
        jButtonCrearRedBarabasiAlbert = new javax.swing.JButton();
        jPanelSur = new javax.swing.JPanel();
        jPanelNombreArchivo = new javax.swing.JPanel();
        jLabelNombreArchivo = new javax.swing.JLabel();
        jTextFieldNombreArchivo = new javax.swing.JTextField();
        jLabelCsv = new javax.swing.JLabel();
        jPanelCarpeta = new javax.swing.JPanel();
        jLabelNombreArchivoCarpeta = new javax.swing.JLabel();
        jLabelNombreCarpeta = new javax.swing.JLabel();
        jButtonSeleccionarCarpeta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelNorte.setLayout(new java.awt.BorderLayout());

        jLabelSeleccioneModelo.setText("Seleccione el modelo de red que desea crear ");
        jPanelNorte.add(jLabelSeleccioneModelo, java.awt.BorderLayout.PAGE_START);

        jTabbedPaneErdosRenry.setLayout(new javax.swing.BoxLayout(jTabbedPaneErdosRenry, javax.swing.BoxLayout.PAGE_AXIS));

        jPanelValorN.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabelValorN.setText("Valor de N:");
        jPanelValorN.add(jLabelValorN);

        jTextFieldN.setText("jTextField1");
        jPanelValorN.add(jTextFieldN);

        jLabelApunteValorN.setText("(solo valores positivos y enteros)");
        jPanelValorN.add(jLabelApunteValorN);

        jTabbedPaneErdosRenry.add(jPanelValorN);

        jPaneValorP.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabelValorP.setText("Valor de p: ");
        jPaneValorP.add(jLabelValorP);
        jPaneValorP.add(jSliderValorP);

        jTextFieldValorP.setText("jTextField3");
        jPaneValorP.add(jTextFieldValorP);

        jTabbedPaneErdosRenry.add(jPaneValorP);

        jPanelCrearRedErdosRenry.setFocusTraversalPolicyProvider(true);
        jPanelCrearRedErdosRenry.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jButtonCrearRedErdosRenry.setText("Crear red");
        jPanelCrearRedErdosRenry.add(jButtonCrearRedErdosRenry);

        jTabbedPaneErdosRenry.add(jPanelCrearRedErdosRenry);

        jTabbedPane.addTab("Erdös-Renry", jTabbedPaneErdosRenry);

        jTabbedPaneBarabasiAlbert.setLayout(new javax.swing.BoxLayout(jTabbedPaneBarabasiAlbert, javax.swing.BoxLayout.PAGE_AXIS));

        jPanelValorM.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabelValorM.setText("Valor de m:");
        jPanelValorM.add(jLabelValorM);

        jTextFieldValorM.setText("jTextField1");
        jPanelValorM.add(jTextFieldValorM);

        jTabbedPaneBarabasiAlbert.add(jPanelValorM);

        jPanelValorT.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabelValorT.setText("Valor de t:");
        jPanelValorT.add(jLabelValorT);

        jTextFieldValorT.setText("jTextField1");
        jPanelValorT.add(jTextFieldValorT);

        jTabbedPaneBarabasiAlbert.add(jPanelValorT);

        jPanelCrearRedBarabasiAlbert.setFocusTraversalPolicyProvider(true);
        jPanelCrearRedBarabasiAlbert.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jButtonCrearRedBarabasiAlbert.setText("Crear red");
        jPanelCrearRedBarabasiAlbert.add(jButtonCrearRedBarabasiAlbert);

        jTabbedPaneBarabasiAlbert.add(jPanelCrearRedBarabasiAlbert);

        jTabbedPane.addTab("Barabasi-Albert", jTabbedPaneBarabasiAlbert);

        jPanelNorte.add(jTabbedPane, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanelNorte, java.awt.BorderLayout.CENTER);

        jPanelSur.setLayout(new javax.swing.BoxLayout(jPanelSur, javax.swing.BoxLayout.PAGE_AXIS));

        jPanelNombreArchivo.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabelNombreArchivo.setText("Nombre de archivo de salida:");
        jPanelNombreArchivo.add(jLabelNombreArchivo);

        jTextFieldNombreArchivo.setText("Introduzca nombre                                                         ");
        jTextFieldNombreArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreArchivoActionPerformed(evt);
            }
        });
        jPanelNombreArchivo.add(jTextFieldNombreArchivo);

        jLabelCsv.setText(".csv");
        jPanelNombreArchivo.add(jLabelCsv);

        jPanelSur.add(jPanelNombreArchivo);

        jPanelCarpeta.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jLabelNombreArchivoCarpeta.setText(" El archivo");
        jPanelCarpeta.add(jLabelNombreArchivoCarpeta);

        jLabelNombreCarpeta.setText("se guardará en ...");
        jPanelCarpeta.add(jLabelNombreCarpeta);

        jButtonSeleccionarCarpeta.setText("Carpeta");
        jButtonSeleccionarCarpeta.setToolTipText("");
        jButtonSeleccionarCarpeta.setAutoscrolls(true);
        jButtonSeleccionarCarpeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeleccionarCarpetaActionPerformed(evt);
            }
        });
        jPanelCarpeta.add(jButtonSeleccionarCarpeta);

        jPanelSur.add(jPanelCarpeta);

        getContentPane().add(jPanelSur, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNombreArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreArchivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreArchivoActionPerformed

    private void jButtonSeleccionarCarpetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeleccionarCarpetaActionPerformed
        //fileChooser.setVisible(true);
        
        //fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        
       // rutaCarpeta = fileChooser.getSelectedFile().getAbsolutePath();
        //jLabelNombreArchivoCarpeta.setText(rutaCarpeta);
    }//GEN-LAST:event_jButtonSeleccionarCarpetaActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCrearRedBarabasiAlbert;
    private javax.swing.JButton jButtonCrearRedErdosRenry;
    private javax.swing.JButton jButtonSeleccionarCarpeta;
    private javax.swing.JLabel jLabelApunteValorN;
    private javax.swing.JLabel jLabelCsv;
    private javax.swing.JLabel jLabelNombreArchivo;
    private javax.swing.JLabel jLabelNombreArchivoCarpeta;
    private javax.swing.JLabel jLabelNombreCarpeta;
    private javax.swing.JLabel jLabelSeleccioneModelo;
    private javax.swing.JLabel jLabelValorM;
    private javax.swing.JLabel jLabelValorN;
    private javax.swing.JLabel jLabelValorP;
    private javax.swing.JLabel jLabelValorT;
    private javax.swing.JPanel jPaneValorP;
    private javax.swing.JPanel jPanelCarpeta;
    private javax.swing.JPanel jPanelCrearRedBarabasiAlbert;
    private javax.swing.JPanel jPanelCrearRedErdosRenry;
    private javax.swing.JPanel jPanelNombreArchivo;
    private javax.swing.JPanel jPanelNorte;
    private javax.swing.JPanel jPanelSur;
    private javax.swing.JPanel jPanelValorM;
    private javax.swing.JPanel jPanelValorN;
    private javax.swing.JPanel jPanelValorT;
    private javax.swing.JSlider jSliderValorP;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JPanel jTabbedPaneBarabasiAlbert;
    private javax.swing.JPanel jTabbedPaneErdosRenry;
    private javax.swing.JTextField jTextFieldN;
    private javax.swing.JTextField jTextFieldNombreArchivo;
    private javax.swing.JTextField jTextFieldValorM;
    private javax.swing.JTextField jTextFieldValorP;
    private javax.swing.JTextField jTextFieldValorT;
    // End of variables declaration//GEN-END:variables
}
